<a href="https://colab.research.google.com/github/christophergarcia89/machinelearning-az/blob/master/datasets/Part%201%20-%20Data%20Preprocessing/Section%202%20--------------------%20Part%201%20-%20Data%20Preprocessing%20--------------------/data_preprocessing_template_new_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clonamos el repositorio para obtener los dataSet

In [1]:
!git clone https://github.com/joanby/machinelearning-az.git

Cloning into 'machinelearning-az'...
remote: Enumerating objects: 10497, done.
remote: Total 10497 (delta 0), reused 0 (delta 0), pack-reused 10497
Receiving objects: 100% (10497/10497), 310.48 MiB | 35.15 MiB/s, done.
Resolving deltas: 100% (213/213), done.
Checking out files: 100% (10250/10250), done.


# Damos acceso a nuestro Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Test it

In [3]:
!ls '/content/drive/My Drive' 

 20200716_171004.jpg
 20200716_171009.jpg
 20200716_171018.jpg
 aban17.rar
 All-App-Inventor-Projects.zip
'Análisis de Algoritmo'
 Apuntes.gdoc
 borrado_carpetas_SAPG01.txt.gdoc
'Captura y almacenamiento'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (10).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (11).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (1).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (2).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (3).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (4).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (5).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (6).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (7).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (8).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV (9).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV - Christopher Garcia (1).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV - Christopher Garcia (2).pdf'
'CHRISTOPHER ALEJADRO GARCIA CISTERNA_CV - Christopher Garcia (3).pdf'
'CHRISTOPHER ALEJADRO GARCIA 

#Google colab tools

In [4]:
from google.colab import files # Para manejar los archivos y, por ejemplo, exportar a su navegador
import glob # Para manejar los archivos y, por ejemplo, exportar a su navegador
from google.colab import drive # Montar tu Google drive

# Plantilla de Pre Procesado

# Cómo importar las librerías


In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [11]:
dataset = pd.read_csv('/content/machinelearning-az/datasets/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data.csv')
#Para extraer las variables independientes del dataset
X = dataset.iloc[:, :-1].values
#Para extraer la variable dependiente o variable a predecir
y = dataset.iloc[:, 3].values
print(dataset)
print(X)
print(y)


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Tratamiento de los NAs

In [13]:
from sklearn.impute import SimpleImputer

In [16]:
#Para reemplazar los valores NA y modificarlos por la media de los valores de las columnas
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean", verbose=0)
#Al crear imputer, vamos a sustituir los valores de las variables independientes (X) de las columnas Age y Salary.
imputer = imputer.fit(X[:,1:3]) 
X[:, 1:3] = imputer.transform(X[:,1:3])
print(X[:, 1:3])

[[44.0 72000.0]
 [27.0 48000.0]
 [30.0 54000.0]
 [38.0 61000.0]
 [40.0 63777.77777777778]
 [35.0 58000.0]
 [38.77777777777778 52000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [37.0 67000.0]]


# Codificar datos categoricos

In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [20]:
#Crear un codificador de datos
labelencoder_X = LabelEncoder()
#Transforma y codifica las columnas
#X[:, 0] -> trae todas las filas ":" y la primera columna que serian los paises
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
#Reemplaza las variables a categoricas, en este caso para los paises
print(X[:, 0])
print(X)

[0 2 1 2 1 0 2 0 1 0]
[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [26]:
#Genera variables dummy para las variables del dataset original, reemplazando por 0 y 1
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                        
)

In [24]:
#Generar variables dummy para las variables independientes
X = np.array(ct.fit_transform(X), dtype=np.float)
#Variables dummy para la variable dependiente. Los Yes y No, se reemplazan por 0 y 1
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(X)
print(y)


[[1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [1.000000

# Dividir el data set en conjunto de entrenamiento y conjunto de testing


In [27]:
from sklearn.model_selection import train_test_split

In [29]:
#random_state es para generar la semilla
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [32]:
#Escalar, es la normalización de los datos para que sean comparables entre variables
#La idea es que al comparar no sea por el rango de los valores, sino por la importancia
from sklearn.preprocessing import StandardScaler

In [36]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
#X_test, solo con transform. Ya que viene ya de
X_test = sc_X.transform(X_test)
print(X_train.shape)
print(X_train)
print(X_test.shape)
print(X_test)

(8, 7)
[[-1.          1.         -1.          2.64575131 -0.77459667  0.26306757
   0.12381479]
 [ 1.         -1.          1.         -0.37796447 -0.77459667 -0.25350148
   0.46175632]
 [-1.          1.         -1.         -0.37796447  1.29099445 -1.97539832
  -1.53093341]
 [-1.          1.         -1.         -0.37796447  1.29099445  0.05261351
  -1.11141978]
 [ 1.         -1.          1.         -0.37796447 -0.77459667  1.64058505
   1.7202972 ]
 [-1.          1.         -1.         -0.37796447  1.29099445 -0.0813118
  -0.16751412]
 [ 1.         -1.          1.         -0.37796447 -0.77459667  0.95182631
   0.98614835]
 [ 1.         -1.          1.         -0.37796447 -0.77459667 -0.59788085
  -0.48214934]]
(2, 7)
[[-1.          1.         -1.          2.64575131 -0.77459667 -1.45882927
  -0.90166297]
 [-1.          1.         -1.          2.64575131 -0.77459667  1.98496442
   2.13981082]]


In [37]:
result_Xtrain = pd.DataFrame({'Column1': X_train[:, 0], 'Column2': X_train[:, 1],'Column3': X_train[:, 2], 'Column4': X_train[:, 3],'Column5': X_train[:, 4]})

In [38]:
display(result_Xtrain)

Column1  Column2  Column3   Column4   Column5
0     -1.0      1.0     -1.0  2.645751 -0.774597
1      1.0     -1.0      1.0 -0.377964 -0.774597
2     -1.0      1.0     -1.0 -0.377964  1.290994
3     -1.0      1.0     -1.0 -0.377964  1.290994
4      1.0     -1.0      1.0 -0.377964 -0.774597
5     -1.0      1.0     -1.0 -0.377964  1.290994
6      1.0     -1.0      1.0 -0.377964 -0.774597
7      1.0     -1.0      1.0 -0.377964 -0.774597

In [39]:
result_X_test = pd.DataFrame({'Column1': X_test[:, 0], 'Column2': X_test[:, 1],'Column3': X_test[:, 2], 'Column4': X_test[:, 3],'Column5': X_test[:, 4]})

In [40]:
display(result_X_test)

Column1  Column2  Column3   Column4   Column5
0     -1.0      1.0     -1.0  2.645751 -0.774597
1     -1.0      1.0     -1.0  2.645751 -0.774597